[package]
name = "jxr2mp4"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
subprocess = "0.2.9"
toml = "0.9.8"

[build-dependencies]
cc = "1.2.49"
